default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: talenthub_rails_db

test:
  <<: *default
  database: talenthub_rails_test

production:
  primary:
    <<: *default
  cache:
    <<: *default
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    migrations_paths: db/cable_migrate