default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: talenthub_rails_db
  host: localhost
  username: postgres
  password: 123456
  url:  # En desarrollo dejamos la URL vacÃ­a para que use los datos de arriba

test:
  <<: *default
  database: talenthub_rails_test
  host: localhost
  username: postgres
  password: 123456

production:
  <<: *default
  # Forzamos a que todas las funciones usen la misma base de datos de Supabase
  cache:
    <<: *default
  queue:
    <<: *default
  cable:
    <<: *default