default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: talenthub_rails_db
  host: localhost
  username: postgres
  password: 123456
  url: # En desarrollo usamos los datos de arriba

test:
  <<: *default
  database: talenthub_rails_test
  host: localhost
  username: postgres
  password: 123456

production:
  primary: &primary_production
    <<: *default
  # Rails 8 busca especÃ­ficamente estas llaves para los motores Solid
  cache:
    <<: *primary_production
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    migrations_paths: db/cable_migrate