default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: talenthub_rails_db
  host: localhost
  username: postgres
  password: 123456

test:
  <<: *default
  database: talenthub_rails_test
  host: localhost
  username: postgres
  password: 123456

# EN PRODUCCIÓN IGNORAMOS TODO Y USAMOS LA URL DE SUPABASE
production:
  adapter: postgresql
  # Rails leerá automáticamente la variable DATABASE_URL de Koyeb
  url: <%= ENV['DATABASE_URL'] %>
  # Desactivamos las bases de datos extra de Rails 8 para que no rompa Supabase
  cache:
    adapter: postgresql
    url: <%= ENV['DATABASE_URL'] %>
  queue:
    adapter: postgresql
    url: <%= ENV['DATABASE_URL'] %>
  cable:
    adapter: postgresql
    url: <%= ENV['DATABASE_URL'] %>