default: &default
  adapter: postgresql
  encoding: unicode
  # Aumentamos un poco el pool para manejar mejor las ráfagas del Dashboard
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: talenthub_rails_db

test:
  <<: *default
  database: talenthub_rails_test

production:
  primary: &primary_production
    <<: *default
    # ESTO ES LO MÁS IMPORTANTE: evita los errores de protocolo en Supabase/Render
    prepared_statements: false
  
  # Si usas Solid Cache o Solid Queue (Rails 8), aplica también aquí:
  cache:
    <<: *primary_production
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    migrations_paths: db/cable_migrate